[build]
  command = "rm -rf .next && npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"
  npm_config_cache = "/opt/build/cache/npm"

[[plugins]]
  package = "@netlify/plugin-nextjs"
